/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{twig,html,js}',
    './templates/**/*.{twig,html}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  safelist: [
    // Text-bg utilities (used dynamically in badge component)
    'text-bg-primary',
    'text-bg-secondary',
    'text-bg-success',
    'text-bg-danger',
    'text-bg-warning',
    'text-bg-info',
    'text-bg-light',
    'text-bg-dark',
    // Shadow utilities (used dynamically in blockquote and other components)
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    // Button variant colors (used dynamically in button component)
    'bg-yellow-500',
    'bg-yellow-600',
    'bg-blue-500',
    'bg-blue-600',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-800',
    'bg-gray-900',
    'text-yellow-600',
    'text-blue-600',
    'text-gray-600',
    'text-gray-800',
    'text-gray-900',
    'border-green-600',
    'border-red-600',
    'border-yellow-600',
    'border-blue-600',
    'border-gray-400',
    'border-gray-800',
    'focus:ring-yellow-500',
    'focus:ring-blue-500',
    'focus:ring-green-500',
    'focus:ring-red-500',
    'focus:ring-gray-100',
    'focus:ring-gray-800',
    'hover:bg-green-600',
    'hover:bg-red-600',
    'hover:bg-yellow-600',
    'hover:bg-blue-600',
    'hover:bg-gray-100',
    'hover:bg-gray-200',
    'hover:bg-gray-800',
    'hover:bg-gray-900',
    // Divider styles (used dynamically in divider component)
    'border-solid',
    'border-dashed',
    'border-dotted',
    'border-double',
    // Divider colors
    'border-gray-200',
    'border-gray-300',
    'border-gray-700',
    // Divider sizes (fractional widths/heights) - explicit class names
    'w-1/4',
    'w-1/2',
    'w-3/4',
    'h-1/4',
    'h-1/2',
    'h-3/4',
    // Also add with margin auto classes for alignment
    'mx-auto',
    'mr-auto',
    'ml-auto',
    'ml-0',
    'mr-0',
    'my-auto',
    'mt-auto',
    'mb-auto',
    'mt-0',
    'mb-0',
  ],
  theme: {
    extend: {
      colors: {
        // Cheppers brand colors
        primary: {
          DEFAULT: '#20b9f5',
          50: '#e8f8fe',
          100: '#d1f1fd',
          200: '#a3e3fb',
          300: '#75d5f9',
          400: '#47c7f7',
          500: '#20b9f5',
          600: '#1a94c4',
          700: '#136f93',
          800: '#0d4a62',
          900: '#062531',
        },
        secondary: {
          DEFAULT: '#1bfcbe',
          50: '#e7fef7',
          100: '#cffdef',
          200: '#9ffbdf',
          300: '#6ff9cf',
          400: '#3ff7bf',
          500: '#1bfcbe',
          600: '#16ca98',
          700: '#109772',
          800: '#0b654c',
          900: '#053226',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        heading: ['Poppins', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
