/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{twig,html,js}',
    './templates/**/*.{twig,html}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  safelist: [
    // Pattern-based safelist for color component (supports all shades 50-900)
    // This protects dynamically generated classes from purging
    {
      pattern: /^(text|bg|border)-(red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose|slate|gray|zinc|neutral|stone)-(50|100|200|300|400|500|600|700|800|900)$/,
    },
    // Simplified 7-color palette
    'text-primary',
    'text-secondary',
    'text-tertiary',
    'text-white',
    'text-black',
    'text-gray-600', // light
    'text-gray-800', // dark
    'bg-primary',
    'bg-secondary',
    'bg-tertiary',
    'bg-white',
    'bg-black',
    'bg-gray-200', // light
    'bg-gray-800', // dark
    'border-primary',
    'border-secondary',
    'border-tertiary',
    'border-white',
    'border-black',
    'border-gray-300', // light/white border
    'border-gray-800', // dark
    // Text-bg utilities (old Bootstrap-style, keeping for compatibility)
    'text-bg-primary',
    'text-bg-secondary',
    'text-bg-success',
    'text-bg-danger',
    'text-bg-warning',
    'text-bg-info',
    'text-bg-light',
    'text-bg-dark',
    'text-bg-white',
    'text-bg-black',
    // Shadow utilities (used dynamically in blockquote and other components)
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    // Button variant colors (used dynamically in button component)
    'bg-yellow-500',
    'bg-yellow-600',
    'bg-blue-500',
    'bg-blue-600',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-800',
    'bg-gray-900',
    'text-yellow-600',
    'text-blue-600',
    'text-gray-600',
    'text-gray-800',
    'text-gray-900',
    'text-white',
    'text-black',
    'border-green-600',
    'border-red-600',
    'border-yellow-600',
    'border-blue-600',
    'border-gray-400',
    'border-gray-800',
    'border-white',
    'border-black',
    'focus:ring-yellow-500',
    'focus:ring-blue-500',
    'focus:ring-green-500',
    'focus:ring-red-500',
    'focus:ring-gray-100',
    'focus:ring-gray-800',
    'hover:bg-green-600',
    'hover:bg-red-600',
    'hover:bg-yellow-600',
    'hover:bg-blue-600',
    'hover:bg-gray-100',
    'hover:bg-gray-200',
    'hover:bg-gray-800',
    'hover:bg-gray-900',
    // Divider styles (used dynamically in divider component)
    'border-solid',
    'border-dashed',
    'border-dotted',
    'border-double',
    // Divider thickness
    'border-t',
    'border-t-2',
    'border-t-4',
    'border-t-6',
    'border-l',
    'border-l-2',
    'border-l-4',
    'border-l-6',
    // Gradient divider
    'bg-gradient-to-r',
    'bg-gradient-to-b',
    'from-primary',
    'to-secondary',
    'h-px',
    'h-1',
    'h-1.5',
    'w-px',
    'w-1',
    'w-1.5',
    'min-h-4',
    'align-middle',
    // Grid col-span classes (used in two-column, three-column, four-column containers)
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-6',
    'col-span-8',
    'col-span-9',
    'sm:col-span-1',
    'sm:col-span-2',
    'sm:col-span-3',
    'sm:col-span-4',
    'sm:col-span-6',
    'sm:col-span-8',
    'sm:col-span-9',
    'md:col-span-1',
    'md:col-span-2',
    'md:col-span-3',
    'md:col-span-4',
    'md:col-span-6',
    'md:col-span-8',
    'md:col-span-9',
    'lg:col-span-1',
    'lg:col-span-2',
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-6',
    'lg:col-span-8',
    'lg:col-span-9',
    // Grid cols classes (used in container layouts)
    'sm:grid-cols-3',
    'sm:grid-cols-4',
    'sm:grid-cols-12',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'md:grid-cols-12',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'lg:grid-cols-12',
    // Hero padding classes (large vertical padding)
    'py-32',
    'py-40',
    'py-48',
    'py-56',
    'py-64',
    'py-72',
    'sm:py-40',
    'sm:py-48',
    'sm:py-56',
    'sm:py-64',
    'sm:py-72',
    'lg:py-56',
    'lg:py-64',
    'lg:py-72',
    // Divider colors
    'border-gray-200',
    'border-gray-300',
    'border-gray-700',
    // Divider sizes (fractional widths/heights) - explicit class names
    'w-1/4',
    'w-1/2',
    'w-3/4',
    'h-1/4',
    'h-1/2',
    'h-3/4',
    // Also add with margin auto classes for alignment
    'mx-auto',
    'mr-auto',
    'ml-auto',
    'ml-0',
    'mr-0',
    'my-auto',
    'mt-auto',
    'mb-auto',
    'mt-0',
    'mb-0',
    // Component spacing utilities (used in spacing prop)
    'mt-6',
    'mr-6',
    'mb-6',
    'ml-6',
    'my-6',
    'mx-6',
    // Card variant classes
    'bg-gray-900',
    'text-gray-900',
    'rounded-3xl',
    'border-2',
    'border-primary',
    'bg-primary',
    'bg-secondary',
    'hover:shadow-xl',
    'hover:-translate-y-1',
    // Heading font sizes (h1-h6)
    'text-5xl',
    'text-4xl',
    'text-3xl',
    'text-2xl',
    'text-xl',
    'text-lg',
    // List types (used dynamically in ordered-list and unordered-list components)
    'list-decimal',
    'list-upper-alpha',
    'list-lower-alpha',
    'list-upper-roman',
    'list-lower-roman',
    'list-none',
    'list-disc',
    'list-circle',
    'list-square',
    // List spacing (vertical and horizontal)
    'space-y-1',
    'space-y-2',
    'space-y-4',
    'space-x-4',
    'space-x-6',
    'space-x-8',
    'space-x-10',
    // Ordered list marker colors (pattern-based for all shades)
    {
      pattern: /^marker:text-(red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose|slate|gray|zinc|neutral|stone)-(50|100|200|300|400|500|600|700|800|900)$/,
      variants: ['marker'],
    },
    'marker:text-primary',
    'marker:text-secondary',
    'marker:text-white',
    'marker:text-black',
    'marker:text-gray-300', // light
    'marker:text-gray-800', // dark
    // Opacity backgrounds for video components
    'bg-black/60',
    'bg-black/80',
    'bg-white/60',
    'bg-white/80',
    'hover:bg-black/80',
    'hover:bg-white/80',
  ],
  theme: {
    extend: {
      colors: {
        // Brand colors
        primary: {
          DEFAULT: '#20b9f5',
          50: '#e8f8fe',
          100: '#d1f1fd',
          200: '#a3e3fb',
          300: '#75d5f9',
          400: '#47c7f7',
          500: '#20b9f5',
          600: '#1a94c4',
          700: '#136f93',
          800: '#0d4a62',
          900: '#062531',
        },
        secondary: {
          DEFAULT: '#1bfcbe',
          50: '#e7fef7',
          100: '#cffdef',
          200: '#9ffbdf',
          300: '#6ff9cf',
          400: '#3ff7bf',
          500: '#1bfcbe',
          600: '#16ca98',
          700: '#109772',
          800: '#0b654c',
          900: '#053226',
        },
        tertiary: {
          DEFAULT: '#773cf5',
          50: '#f3ecfe',
          100: '#e7d9fd',
          200: '#cfb3fb',
          300: '#b78df9',
          400: '#9f67f7',
          500: '#773cf5',
          600: '#5f30c4',
          700: '#472493',
          800: '#301862',
          900: '#180c31',
        },
      },
      borderWidth: {
        DEFAULT: '1px',
        '0': '0px',
        '2': '2px',
        '4': '4px',
        '6': '6px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        heading: ['Poppins', 'sans-serif'],
      },
      listStyleType: {
        none: 'none',
        disc: 'disc',
        circle: 'circle',
        square: 'square',
        decimal: 'decimal',
        'upper-alpha': 'upper-alpha',
        'lower-alpha': 'lower-alpha',
        'upper-roman': 'upper-roman',
        'lower-roman': 'lower-roman',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
