#!/bin/bash

## #ddev-generated
## Description: (Re)install Drupal and the Drupal Canvas module.
## Example: ddev xb-site-install
## Aliases: site-install,si

# Install Drupal.
drush site:install -y \
  --account-name=admin \
  --account-pass=admin \
  --site-name="Drupal Canvas Local Dev"

# Enable the Canvas module.
drush pm:install -y \
  canvas \
  canvas_dev_mode \
  sdc_test_all_props

# Without a cache rebuild, Drupal can't find test modules, leading to a WSOD.
drush cache:rebuild

# Display a one time login link for user ID 1.
drush uli
