#!/bin/bash

## #ddev-generated
## Description: Clean-install and build Drupal Canvas' UI app assets.
## Example: ddev xb-ui-build
## Aliases: ui-build,build

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/canvas/ui" || exit 1

drush pm:uninstall canvas_vite -y > /dev/null 2>&1 || :
npm ci
npm run build
